-- --------------------------------------------------------
-- Hôte :                        localhost
-- Version du serveur:           5.7.18 - MySQL Community Server (GPL)
-- SE du serveur:                Win64
-- HeidiSQL Version:             9.4.0.5125
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Export de données de la table bdd_projet.categories : ~126 rows (environ)
/*!40000 ALTER TABLE `categories` DISABLE KEYS */;
INSERT INTO `categories` (`id_category`, `genre`) VALUES
	(1, 'acoustic'),
	(2, 'afrobeat'),
	(3, 'alt-rock'),
	(4, 'alternative'),
	(5, 'ambient'),
	(6, 'anime'),
	(7, 'black-metal'),
	(8, 'bluegrass'),
	(9, 'blues'),
	(10, 'bossanova'),
	(11, 'brazil'),
	(12, 'breakbeat'),
	(13, 'british'),
	(14, 'cantopop'),
	(15, 'chicago-house'),
	(16, 'children'),
	(17, 'chill'),
	(18, 'classical'),
	(19, 'club'),
	(20, 'comedy'),
	(21, 'country'),
	(22, 'dance'),
	(23, 'dancehall'),
	(24, 'death-metal'),
	(25, 'deep-house'),
	(26, 'detroit-techno'),
	(27, 'disco'),
	(28, 'disney'),
	(29, 'drum-and-bass'),
	(30, 'dub'),
	(31, 'dubstep'),
	(32, 'edm'),
	(33, 'electro'),
	(34, 'electronic'),
	(35, 'emo'),
	(36, 'folk'),
	(37, 'forro'),
	(38, 'french'),
	(39, 'funk'),
	(40, 'garage'),
	(41, 'german'),
	(42, 'gospel'),
	(43, 'goth'),
	(44, 'grindcore'),
	(45, 'groove'),
	(46, 'grunge'),
	(47, 'guitar'),
	(48, 'happy'),
	(49, 'hard-rock'),
	(50, 'hardcore'),
	(51, 'hardstyle'),
	(52, 'heavy-metal'),
	(53, 'hip-hop'),
	(54, 'holidays'),
	(55, 'honky-tonk'),
	(56, 'house'),
	(57, 'idm'),
	(58, 'indian'),
	(59, 'indie'),
	(60, 'indie-pop'),
	(61, 'industrial'),
	(62, 'iranian'),
	(63, 'j-dance'),
	(64, 'j-idol'),
	(65, 'j-pop'),
	(66, 'j-rock'),
	(67, 'jazz'),
	(68, 'k-pop'),
	(69, 'kids'),
	(70, 'latin'),
	(71, 'latino'),
	(72, 'malay'),
	(73, 'mandopop'),
	(74, 'metal'),
	(75, 'metal-misc'),
	(76, 'metalcore'),
	(77, 'minimal-techno'),
	(78, 'movies'),
	(79, 'mpb'),
	(80, 'new-age'),
	(81, 'new-release'),
	(82, 'opera'),
	(83, 'pagode'),
	(84, 'party'),
	(85, 'philippines-opm'),
	(86, 'piano'),
	(87, 'pop'),
	(88, 'pop-film'),
	(89, 'post-dubstep'),
	(90, 'power-pop'),
	(91, 'progressive-house'),
	(92, 'psych-rock'),
	(93, 'punk'),
	(94, 'punk-rock'),
	(95, 'r-n-b'),
	(96, 'rainy-day'),
	(97, 'reggae'),
	(98, 'reggaeton'),
	(99, 'road-trip'),
	(100, 'rock'),
	(101, 'rock-n-roll'),
	(102, 'rockabilly'),
	(103, 'romance'),
	(104, 'sad'),
	(105, 'salsa'),
	(106, 'samba'),
	(107, 'sertanejo'),
	(108, 'show-tunes'),
	(109, 'singer-songwriter'),
	(110, 'ska'),
	(111, 'sleep'),
	(112, 'songwriter'),
	(113, 'soul'),
	(114, 'soundtracks'),
	(115, 'spanish'),
	(116, 'study'),
	(117, 'summer'),
	(118, 'swedish'),
	(119, 'synth-pop'),
	(120, 'tango'),
	(121, 'techno'),
	(122, 'trance'),
	(123, 'trip-hop'),
	(124, 'turkish'),
	(125, 'work-out'),
	(126, 'world-music');
/*!40000 ALTER TABLE `categories` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
